/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientTimelineRouteImport } from './routes/patient.timeline'
import { Route as PatientReportsRouteImport } from './routes/patient.reports'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientPrescriptionsRouteImport } from './routes/patient.prescriptions'
import { Route as PatientDashboardRouteImport } from './routes/patient.dashboard'
import { Route as DoctorReviewsRouteImport } from './routes/doctor.reviews'
import { Route as DoctorQueueRouteImport } from './routes/doctor.queue'
import { Route as DoctorPatientsRouteImport } from './routes/doctor.patients'
import { Route as DoctorDashboardRouteImport } from './routes/doctor.dashboard'
import { Route as DoctorAppointmentsRouteImport } from './routes/doctor.appointments'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminHospitalSettingsRouteImport } from './routes/admin.hospital-settings'
import { Route as AdminDoctorsRouteImport } from './routes/admin.doctors'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminAiModelsRouteImport } from './routes/admin.ai-models'
import { Route as PatientTreatmentsOngoingRouteImport } from './routes/patient.treatments.ongoing'
import { Route as PatientTreatmentsHistoryRouteImport } from './routes/patient.treatments.history'
import { Route as PatientConsultationNewRouteImport } from './routes/patient.consultation.new'
import { Route as PatientConsultationIdRouteImport } from './routes/patient.consultation.$id'
import { Route as DoctorConsultationsIdRouteImport } from './routes/doctor.consultations.$id'
import { Route as PatientTreatmentsHistoryIdRouteImport } from './routes/patient.treatments.history.$id'
import { Route as PatientConsultationIdReportRouteImport } from './routes/patient.consultation.$id.report'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientTimelineRoute = PatientTimelineRouteImport.update({
  id: '/patient/timeline',
  path: '/patient/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientReportsRoute = PatientReportsRouteImport.update({
  id: '/patient/reports',
  path: '/patient/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/patient/profile',
  path: '/patient/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPrescriptionsRoute = PatientPrescriptionsRouteImport.update({
  id: '/patient/prescriptions',
  path: '/patient/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientDashboardRoute = PatientDashboardRouteImport.update({
  id: '/patient/dashboard',
  path: '/patient/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorReviewsRoute = DoctorReviewsRouteImport.update({
  id: '/doctor/reviews',
  path: '/doctor/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorQueueRoute = DoctorQueueRouteImport.update({
  id: '/doctor/queue',
  path: '/doctor/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/doctor/patients',
  path: '/doctor/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorDashboardRoute = DoctorDashboardRouteImport.update({
  id: '/doctor/dashboard',
  path: '/doctor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorAppointmentsRoute = DoctorAppointmentsRouteImport.update({
  id: '/doctor/appointments',
  path: '/doctor/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHospitalSettingsRoute = AdminHospitalSettingsRouteImport.update({
  id: '/admin/hospital-settings',
  path: '/admin/hospital-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/admin/doctors',
  path: '/admin/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiModelsRoute = AdminAiModelsRouteImport.update({
  id: '/admin/ai-models',
  path: '/admin/ai-models',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientTreatmentsOngoingRoute =
  PatientTreatmentsOngoingRouteImport.update({
    id: '/patient/treatments/ongoing',
    path: '/patient/treatments/ongoing',
    getParentRoute: () => rootRouteImport,
  } as any)
const PatientTreatmentsHistoryRoute =
  PatientTreatmentsHistoryRouteImport.update({
    id: '/patient/treatments/history',
    path: '/patient/treatments/history',
    getParentRoute: () => rootRouteImport,
  } as any)
const PatientConsultationNewRoute = PatientConsultationNewRouteImport.update({
  id: '/patient/consultation/new',
  path: '/patient/consultation/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientConsultationIdRoute = PatientConsultationIdRouteImport.update({
  id: '/patient/consultation/$id',
  path: '/patient/consultation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorConsultationsIdRoute = DoctorConsultationsIdRouteImport.update({
  id: '/doctor/consultations/$id',
  path: '/doctor/consultations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientTreatmentsHistoryIdRoute =
  PatientTreatmentsHistoryIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => PatientTreatmentsHistoryRoute,
  } as any)
const PatientConsultationIdReportRoute =
  PatientConsultationIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => PatientConsultationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/ai-models': typeof AdminAiModelsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/hospital-settings': typeof AdminHospitalSettingsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/queue': typeof DoctorQueueRoute
  '/doctor/reviews': typeof DoctorReviewsRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/timeline': typeof PatientTimelineRoute
  '/doctor/consultations/$id': typeof DoctorConsultationsIdRoute
  '/patient/consultation/$id': typeof PatientConsultationIdRouteWithChildren
  '/patient/consultation/new': typeof PatientConsultationNewRoute
  '/patient/treatments/history': typeof PatientTreatmentsHistoryRouteWithChildren
  '/patient/treatments/ongoing': typeof PatientTreatmentsOngoingRoute
  '/patient/consultation/$id/report': typeof PatientConsultationIdReportRoute
  '/patient/treatments/history/$id': typeof PatientTreatmentsHistoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/ai-models': typeof AdminAiModelsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/hospital-settings': typeof AdminHospitalSettingsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/queue': typeof DoctorQueueRoute
  '/doctor/reviews': typeof DoctorReviewsRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/timeline': typeof PatientTimelineRoute
  '/doctor/consultations/$id': typeof DoctorConsultationsIdRoute
  '/patient/consultation/$id': typeof PatientConsultationIdRouteWithChildren
  '/patient/consultation/new': typeof PatientConsultationNewRoute
  '/patient/treatments/history': typeof PatientTreatmentsHistoryRouteWithChildren
  '/patient/treatments/ongoing': typeof PatientTreatmentsOngoingRoute
  '/patient/consultation/$id/report': typeof PatientConsultationIdReportRoute
  '/patient/treatments/history/$id': typeof PatientTreatmentsHistoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/ai-models': typeof AdminAiModelsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/hospital-settings': typeof AdminHospitalSettingsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/queue': typeof DoctorQueueRoute
  '/doctor/reviews': typeof DoctorReviewsRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/timeline': typeof PatientTimelineRoute
  '/doctor/consultations/$id': typeof DoctorConsultationsIdRoute
  '/patient/consultation/$id': typeof PatientConsultationIdRouteWithChildren
  '/patient/consultation/new': typeof PatientConsultationNewRoute
  '/patient/treatments/history': typeof PatientTreatmentsHistoryRouteWithChildren
  '/patient/treatments/ongoing': typeof PatientTreatmentsOngoingRoute
  '/patient/consultation/$id/report': typeof PatientConsultationIdReportRoute
  '/patient/treatments/history/$id': typeof PatientTreatmentsHistoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/ai-models'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/hospital-settings'
    | '/admin/permissions'
    | '/admin/users'
    | '/doctor/appointments'
    | '/doctor/dashboard'
    | '/doctor/patients'
    | '/doctor/queue'
    | '/doctor/reviews'
    | '/patient/dashboard'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/patient/reports'
    | '/patient/timeline'
    | '/doctor/consultations/$id'
    | '/patient/consultation/$id'
    | '/patient/consultation/new'
    | '/patient/treatments/history'
    | '/patient/treatments/ongoing'
    | '/patient/consultation/$id/report'
    | '/patient/treatments/history/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/ai-models'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/hospital-settings'
    | '/admin/permissions'
    | '/admin/users'
    | '/doctor/appointments'
    | '/doctor/dashboard'
    | '/doctor/patients'
    | '/doctor/queue'
    | '/doctor/reviews'
    | '/patient/dashboard'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/patient/reports'
    | '/patient/timeline'
    | '/doctor/consultations/$id'
    | '/patient/consultation/$id'
    | '/patient/consultation/new'
    | '/patient/treatments/history'
    | '/patient/treatments/ongoing'
    | '/patient/consultation/$id/report'
    | '/patient/treatments/history/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/admin/ai-models'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/hospital-settings'
    | '/admin/permissions'
    | '/admin/users'
    | '/doctor/appointments'
    | '/doctor/dashboard'
    | '/doctor/patients'
    | '/doctor/queue'
    | '/doctor/reviews'
    | '/patient/dashboard'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/patient/reports'
    | '/patient/timeline'
    | '/doctor/consultations/$id'
    | '/patient/consultation/$id'
    | '/patient/consultation/new'
    | '/patient/treatments/history'
    | '/patient/treatments/ongoing'
    | '/patient/consultation/$id/report'
    | '/patient/treatments/history/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AdminAiModelsRoute: typeof AdminAiModelsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminHospitalSettingsRoute: typeof AdminHospitalSettingsRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  DoctorAppointmentsRoute: typeof DoctorAppointmentsRoute
  DoctorDashboardRoute: typeof DoctorDashboardRoute
  DoctorPatientsRoute: typeof DoctorPatientsRoute
  DoctorQueueRoute: typeof DoctorQueueRoute
  DoctorReviewsRoute: typeof DoctorReviewsRoute
  PatientDashboardRoute: typeof PatientDashboardRoute
  PatientPrescriptionsRoute: typeof PatientPrescriptionsRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientReportsRoute: typeof PatientReportsRoute
  PatientTimelineRoute: typeof PatientTimelineRoute
  DoctorConsultationsIdRoute: typeof DoctorConsultationsIdRoute
  PatientConsultationIdRoute: typeof PatientConsultationIdRouteWithChildren
  PatientConsultationNewRoute: typeof PatientConsultationNewRoute
  PatientTreatmentsHistoryRoute: typeof PatientTreatmentsHistoryRouteWithChildren
  PatientTreatmentsOngoingRoute: typeof PatientTreatmentsOngoingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/timeline': {
      id: '/patient/timeline'
      path: '/patient/timeline'
      fullPath: '/patient/timeline'
      preLoaderRoute: typeof PatientTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/reports': {
      id: '/patient/reports'
      path: '/patient/reports'
      fullPath: '/patient/reports'
      preLoaderRoute: typeof PatientReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/patient/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/prescriptions': {
      id: '/patient/prescriptions'
      path: '/patient/prescriptions'
      fullPath: '/patient/prescriptions'
      preLoaderRoute: typeof PatientPrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/dashboard': {
      id: '/patient/dashboard'
      path: '/patient/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof PatientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/reviews': {
      id: '/doctor/reviews'
      path: '/doctor/reviews'
      fullPath: '/doctor/reviews'
      preLoaderRoute: typeof DoctorReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/queue': {
      id: '/doctor/queue'
      path: '/doctor/queue'
      fullPath: '/doctor/queue'
      preLoaderRoute: typeof DoctorQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/doctor/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/dashboard': {
      id: '/doctor/dashboard'
      path: '/doctor/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof DoctorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/appointments': {
      id: '/doctor/appointments'
      path: '/doctor/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof DoctorAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hospital-settings': {
      id: '/admin/hospital-settings'
      path: '/admin/hospital-settings'
      fullPath: '/admin/hospital-settings'
      preLoaderRoute: typeof AdminHospitalSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-models': {
      id: '/admin/ai-models'
      path: '/admin/ai-models'
      fullPath: '/admin/ai-models'
      preLoaderRoute: typeof AdminAiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/treatments/ongoing': {
      id: '/patient/treatments/ongoing'
      path: '/patient/treatments/ongoing'
      fullPath: '/patient/treatments/ongoing'
      preLoaderRoute: typeof PatientTreatmentsOngoingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/treatments/history': {
      id: '/patient/treatments/history'
      path: '/patient/treatments/history'
      fullPath: '/patient/treatments/history'
      preLoaderRoute: typeof PatientTreatmentsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/consultation/new': {
      id: '/patient/consultation/new'
      path: '/patient/consultation/new'
      fullPath: '/patient/consultation/new'
      preLoaderRoute: typeof PatientConsultationNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/consultation/$id': {
      id: '/patient/consultation/$id'
      path: '/patient/consultation/$id'
      fullPath: '/patient/consultation/$id'
      preLoaderRoute: typeof PatientConsultationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/consultations/$id': {
      id: '/doctor/consultations/$id'
      path: '/doctor/consultations/$id'
      fullPath: '/doctor/consultations/$id'
      preLoaderRoute: typeof DoctorConsultationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/treatments/history/$id': {
      id: '/patient/treatments/history/$id'
      path: '/$id'
      fullPath: '/patient/treatments/history/$id'
      preLoaderRoute: typeof PatientTreatmentsHistoryIdRouteImport
      parentRoute: typeof PatientTreatmentsHistoryRoute
    }
    '/patient/consultation/$id/report': {
      id: '/patient/consultation/$id/report'
      path: '/report'
      fullPath: '/patient/consultation/$id/report'
      preLoaderRoute: typeof PatientConsultationIdReportRouteImport
      parentRoute: typeof PatientConsultationIdRoute
    }
  }
}

interface PatientConsultationIdRouteChildren {
  PatientConsultationIdReportRoute: typeof PatientConsultationIdReportRoute
}

const PatientConsultationIdRouteChildren: PatientConsultationIdRouteChildren = {
  PatientConsultationIdReportRoute: PatientConsultationIdReportRoute,
}

const PatientConsultationIdRouteWithChildren =
  PatientConsultationIdRoute._addFileChildren(
    PatientConsultationIdRouteChildren,
  )

interface PatientTreatmentsHistoryRouteChildren {
  PatientTreatmentsHistoryIdRoute: typeof PatientTreatmentsHistoryIdRoute
}

const PatientTreatmentsHistoryRouteChildren: PatientTreatmentsHistoryRouteChildren =
  {
    PatientTreatmentsHistoryIdRoute: PatientTreatmentsHistoryIdRoute,
  }

const PatientTreatmentsHistoryRouteWithChildren =
  PatientTreatmentsHistoryRoute._addFileChildren(
    PatientTreatmentsHistoryRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AdminAiModelsRoute: AdminAiModelsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminHospitalSettingsRoute: AdminHospitalSettingsRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  DoctorAppointmentsRoute: DoctorAppointmentsRoute,
  DoctorDashboardRoute: DoctorDashboardRoute,
  DoctorPatientsRoute: DoctorPatientsRoute,
  DoctorQueueRoute: DoctorQueueRoute,
  DoctorReviewsRoute: DoctorReviewsRoute,
  PatientDashboardRoute: PatientDashboardRoute,
  PatientPrescriptionsRoute: PatientPrescriptionsRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientReportsRoute: PatientReportsRoute,
  PatientTimelineRoute: PatientTimelineRoute,
  DoctorConsultationsIdRoute: DoctorConsultationsIdRoute,
  PatientConsultationIdRoute: PatientConsultationIdRouteWithChildren,
  PatientConsultationNewRoute: PatientConsultationNewRoute,
  PatientTreatmentsHistoryRoute: PatientTreatmentsHistoryRouteWithChildren,
  PatientTreatmentsOngoingRoute: PatientTreatmentsOngoingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
